const staticMembers = [
{ name: 'Waawaa', class: 'Paladin', level: 80, rank: 0 },
{ name: 'Waawaasap', class: 'Rogue', level: 80, rank: 1 },
{ name: 'Cucni', class: 'Priest', level: 80, rank: 1 },
{ name: 'Waawaadko', class: 'Death Knight', level: 80, rank: 1 },
{ name: 'Luffytaro', class: 'Warrior', level: 80, rank: 1 },
{ name: 'Tools', class: 'Paladin', level: 80, rank: 1 },
{ name: 'Waawa', class: 'Paladin', level: 80, rank: 1 },
{ name: 'Waawaasham', class: 'Shaman', level: 80, rank: 1 },
{ name: 'Antiopaa', class: 'Paladin', level: 80, rank: 1 },
{ name: 'Coming', class: 'Death Knight', level: 80, rank: 1 },
{ name: 'Waawaaholy', class: 'Paladin', level: 80, rank: 1 },
{ name: 'Waawaameow', class: 'Druid', level: 80, rank: 1 },
{ name: 'Luminaryx', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Availablee', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Lightblast', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Holylight', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Waawaacat', class: 'Druid', level: 80, rank: 4 },
{ name: 'Executr', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Shhadowko', class: 'Priest', level: 80, rank: 4 },
{ name: 'Papawarlock', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Palanator', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Unavaiilable', class: 'Druid', level: 80, rank: 4 },
{ name: 'Wawashield', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Moryena', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Annonce', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Waawaacritz', class: 'Mage', level: 80, rank: 4 },
{ name: 'Siare', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Proshambling', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Fratello', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Chagron', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Holybomb', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Holycreep', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Lasttoon', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Demonstyle', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Chrissy', class: 'Priest', level: 80, rank: 4 },
{ name: 'Waawahuntard', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Waawaapriest', class: 'Priest', level: 80, rank: 4 },
{ name: 'Famale', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Teritoria', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Sihirbringer', class: 'Priest', level: 80, rank: 4 },
{ name: 'Antiopatwo', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Lastelement', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Stoleh', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Rightlight', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Discream', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Cavatenge', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Rayleigh', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Rokanica', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Brule', class: 'Mage', level: 80, rank: 4 },
{ name: 'Papafiremage', class: 'Mage', level: 80, rank: 4 },
{ name: 'Bigbara', class: 'Druid', level: 80, rank: 4 },
{ name: 'Chukkles', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Papafrostdk', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Trajanflame', class: 'Mage', level: 80, rank: 4 },
{ name: 'Arthassdk', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Goldenpali', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Luffythegoat', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Shamkac', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Drugtime', class: 'Druid', level: 80, rank: 4 },
{ name: 'Brigat', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Treestar', class: 'Druid', level: 80, rank: 4 },
{ name: 'Ysl', class: 'Druid', level: 80, rank: 4 },
{ name: 'Shadowkica', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Papaferal', class: 'Druid', level: 80, rank: 4 },
{ name: 'Dydo', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Mancek', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Imbap', class: 'Priest', level: 80, rank: 4 },
{ name: 'Murtral', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Kursadjija', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Vacheronn', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Dartagan', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Trajanoffdk', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Namica', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Arthasindk', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Mordra', class: 'Priest', level: 80, rank: 4 },
{ name: 'Damagus', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Brigato', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Chagrito', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Tsinish', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Yorro', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Meteory', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Khoukh', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Kotk', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Donyaz', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Korbachev', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Trankillo', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Baladin', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Shildboss', class: 'Priest', level: 80, rank: 4 },
{ name: 'Laytnor', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Trajanoff', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Sigurito', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Shmeikel', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Shamacus', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Fatali', class: 'Mage', level: 80, rank: 4 },
{ name: 'Combe', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Jinbej', class: 'Druid', level: 80, rank: 4 },
{ name: 'Flamewish', class: 'Priest', level: 80, rank: 4 },
{ name: 'Critycus', class: 'Mage', level: 80, rank: 4 },
{ name: 'Luffyone', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Parhasard', class: 'Druid', level: 80, rank: 4 },
{ name: 'Hithunter', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Famalee', class: 'Mage', level: 80, rank: 4 },
{ name: 'Nikmagic', class: 'Druid', level: 80, rank: 4 },
{ name: 'Ifuseemeruun', class: 'Mage', level: 80, rank: 4 },
{ name: 'Edomajka', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Irongrave', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Otrovee', class: 'Druid', level: 80, rank: 4 },
{ name: 'Rilebabo', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Rileba', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Rileprist', class: 'Priest', level: 80, rank: 4 },
{ name: 'Goqu', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Sosika', class: 'Mage', level: 80, rank: 4 },
{ name: 'Rilewar', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Rilebosanac', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Zajebancija', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Kenjaj', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Nevaljalaa', class: 'Druid', level: 80, rank: 4 },
{ name: 'Riletata', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Jebenihpala', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Selko', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Favoritoo', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Rilebaa', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Rileferal', class: 'Druid', level: 80, rank: 4 },
{ name: 'Magymage', class: 'Mage', level: 80, rank: 4 },
{ name: 'Rilemagee', class: 'Mage', level: 80, rank: 4 },
{ name: 'Prostakusa', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Riledk', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Dulemage', class: 'Mage', level: 80, rank: 4 },
{ name: 'Rilewarr', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Rileqt', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Riledisco', class: 'Priest', level: 80, rank: 4 },
{ name: 'Prcoljak', class: 'Mage', level: 80, rank: 4 },
{ name: 'Mandzi', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Riledkk', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Rilerog', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Waawaashadow', class: 'Priest', level: 80, rank: 4 },
{ name: 'Halodeath', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Duknukesm', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Riileboss', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Thitania', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Soulbreaker', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Gelosie', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Waawaawarior', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Silvezhina', class: 'Priest', level: 80, rank: 4 },
{ name: 'Capipriest', class: 'Priest', level: 80, rank: 4 },
{ name: 'Hunay', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Reckles', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Gangreene', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Rilesamy', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Nyyxxy', class: 'Mage', level: 80, rank: 4 },
{ name: 'Tryxer', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Tryxerwar', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Shatzii', class: 'Priest', level: 80, rank: 4 },
{ name: 'Povraatnik', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Rastachepsi', class: 'Druid', level: 80, rank: 4 },
{ name: 'Hunterzito', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Extetwarko', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Titos', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Felhart', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Holymastery', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Croma', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Bosanacpala', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Rillesamy', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Icyfck', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Taurenshape', class: 'Druid', level: 80, rank: 4 },
{ name: 'Djubretarka', class: 'Priest', level: 80, rank: 4 },
{ name: 'Ndmiisha', class: 'Mage', level: 80, rank: 4 },
{ name: 'Atreff', class: 'Mage', level: 80, rank: 4 },
{ name: 'Emanyela', class: 'Priest', level: 80, rank: 4 },
{ name: 'Diedbyaggro', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Crazyslashh', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Nordyshaman', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Seerhona', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Smiljanaa', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Strangedude', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Latya', class: 'Mage', level: 80, rank: 4 },
{ name: 'Lynoxqt', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Vizk', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Hegan', class: 'Mage', level: 80, rank: 4 },
{ name: 'Alkaizer', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Leldorin', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Nikoftw', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Suzana', class: 'Mage', level: 80, rank: 4 },
{ name: 'Axestrike', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Mikolatopor', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Straxedix', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Tucaa', class: 'Mage', level: 80, rank: 4 },
{ name: 'Yga', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Doloshamy', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Mecydk', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Sniplock', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Panetone', class: 'Druid', level: 80, rank: 4 },
{ name: 'Sapbringer', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Shadowpdog', class: 'Priest', level: 80, rank: 4 },
{ name: 'Optimizoovan', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Macmiller', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Oceanus', class: 'Druid', level: 80, rank: 4 },
{ name: 'Pyranha', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Manbearcats', class: 'Druid', level: 80, rank: 4 },
{ name: 'Todoresko', class: 'Druid', level: 80, rank: 4 },
{ name: 'Solivete', class: 'Priest', level: 80, rank: 4 },
{ name: 'Pershe', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Midgardqt', class: 'Druid', level: 80, rank: 4 },
{ name: 'Toplavoda', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Xarana', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Landaron', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Stormz', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Facethequen', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Falarona', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Vuzbuden', class: 'Priest', level: 80, rank: 4 },
{ name: 'Pillarman', class: 'Mage', level: 80, rank: 4 },
{ name: 'Cocobill', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Schwepss', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Fryzthp', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Dsalic', class: 'Druid', level: 80, rank: 4 },
{ name: 'Brale', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Packetsix', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Hogback', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Xwtwo', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Sakeza', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Porncow', class: 'Druid', level: 80, rank: 4 },
{ name: 'Cynnical', class: 'Druid', level: 80, rank: 4 },
{ name: 'Ymperador', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Imyouraltt', class: 'Priest', level: 80, rank: 4 },
{ name: 'Holycrys', class: 'Priest', level: 80, rank: 4 },
{ name: 'Kimisham', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Gromkult', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Gorankos', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Kharmhel', class: 'Mage', level: 80, rank: 4 },
{ name: 'Ydor', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Meqaltane', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Drafer', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Jandeyvah', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Unitedforce', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Alrys', class: 'Priest', level: 80, rank: 4 },
{ name: 'Speedcliick', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Druidspawn', class: 'Druid', level: 80, rank: 4 },
{ name: 'Tondeur', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Cylaxh', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Lookatmeetwo', class: 'Druid', level: 80, rank: 4 },
{ name: 'Scumpieqt', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Prepot', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Seldonn', class: 'Priest', level: 80, rank: 4 },
{ name: 'Myexboy', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Trenoverdose', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Alejiny', class: 'Druid', level: 80, rank: 4 },
{ name: 'Sfrjfiliphun', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Icybreeze', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Penatrated', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Fraudz', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Kelthuz', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Ure', class: 'Priest', level: 80, rank: 4 },
{ name: 'Lkimi', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Guthram', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Abithunt', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Zakurac', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Sedefcho', class: 'Druid', level: 80, rank: 4 },
{ name: 'Biencuit', class: 'Mage', level: 80, rank: 4 },
{ name: 'Felkicshotgf', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Aboodpriest', class: 'Priest', level: 80, rank: 4 },
{ name: 'Lingenic', class: 'Mage', level: 80, rank: 4 },
{ name: 'Dontbe', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Invunche', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Bigchibook', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Uchihaa', class: 'Mage', level: 80, rank: 4 },
{ name: 'Darneljr', class: 'Druid', level: 80, rank: 4 },
{ name: 'Elamia', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Mazzika', class: 'Mage', level: 80, rank: 4 },
{ name: 'Frezel', class: 'Druid', level: 80, rank: 4 },
{ name: 'Wenofire', class: 'Mage', level: 80, rank: 4 },
{ name: 'Tomsaller', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Avyra', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Gambid', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Amonic', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Saraxy', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Ggwptyqt', class: 'Mage', level: 80, rank: 4 },
{ name: 'Forstshadow', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Eishblokkie', class: 'Mage', level: 80, rank: 4 },
{ name: 'Zemka', class: 'Priest', level: 80, rank: 4 },
{ name: 'Klonja', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Fdholylegend', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Krimimaus', class: 'Mage', level: 80, rank: 4 },
{ name: 'Ippippipp', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Menonita', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Zecovidrhte', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Neviden', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Ludbrz', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Meganna', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Eemmperror', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Temananc', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Pandorra', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Biancca', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Hunterdcc', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Kyorei', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Chillxgodzx', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Daiharo', class: 'Druid', level: 80, rank: 4 },
{ name: 'Rwargilx', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Luckystrikee', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Terroriszt', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Retrigirl', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Stormheal', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Sides', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Enhance', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Biggueb', class: 'Priest', level: 80, rank: 4 },
{ name: 'Livingatom', class: 'Mage', level: 80, rank: 4 },
{ name: 'Iemilial', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Roy', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Deadluke', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Sacekusa', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Naytiri', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Izpirakuss', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Bichoota', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Hermees', class: 'Priest', level: 80, rank: 4 },
{ name: 'Rumad', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Cocoqt', class: 'Druid', level: 80, rank: 4 },
{ name: 'Zivko', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Barmanen', class: 'Druid', level: 80, rank: 4 },
{ name: 'Warog', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Kommurasaki', class: 'Priest', level: 80, rank: 4 },
{ name: 'Muuchacho', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Chibzfury', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Skeletorz', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Patsani', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Shari', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Wilddheart', class: 'Druid', level: 80, rank: 4 },
{ name: 'Xerxus', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Bojovicluka', class: 'Druid', level: 80, rank: 4 },
{ name: 'Roguemoulinn', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Ustrojen', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Diletta', class: 'Priest', level: 80, rank: 4 },
{ name: 'Siyin', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Manabreath', class: 'Mage', level: 80, rank: 4 },
{ name: 'Lowftw', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Pinkchalk', class: 'Priest', level: 80, rank: 4 },
{ name: 'Deathwishx', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Pekkapappi', class: 'Priest', level: 80, rank: 4 },
{ name: 'Blackblink', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Synchronise', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Blaxus', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Dvinekatana', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Robberr', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Evilpower', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Amritdktank', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Lidri', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Micz', class: 'Mage', level: 80, rank: 4 },
{ name: 'Djenga', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Lysie', class: 'Priest', level: 80, rank: 4 },
{ name: 'Cavare', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Mekambe', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Garanu', class: 'Druid', level: 80, rank: 4 },
{ name: 'Nomsiss', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Mostholy', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Icystorm', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Yrekt', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Kastriot', class: 'Druid', level: 80, rank: 4 },
{ name: 'Fancleavage', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Bercamo', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Slovks', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Onmyouji', class: 'Mage', level: 80, rank: 4 },
{ name: 'Fearllock', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Gadnihunt', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Ninologia', class: 'Mage', level: 80, rank: 4 },
{ name: 'Imbadwolf', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Slyk', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Reinado', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Smallshamy', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Ghorzhuul', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Liqquid', class: 'Priest', level: 80, rank: 4 },
{ name: 'Palakingg', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Belecow', class: 'Druid', level: 80, rank: 4 },
{ name: 'Gift', class: 'Priest', level: 80, rank: 4 },
{ name: 'Yukiimura', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Kgdk', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Valandrea', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Indijanac', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Agdaya', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Soulxsir', class: 'Druid', level: 80, rank: 4 },
{ name: 'Klhuna', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Dcomn', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Ckembarka', class: 'Mage', level: 80, rank: 4 },
{ name: 'Grasshunterr', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Jebendruid', class: 'Druid', level: 80, rank: 4 },
{ name: 'Lulduar', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Cviske', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Bkara', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Cviskelinho', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Narkomanot', class: 'Mage', level: 80, rank: 4 },
{ name: 'Shyte', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Iamninja', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Roxypala', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Tetejacc', class: 'Mage', level: 80, rank: 4 },
{ name: 'Bishamon', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Jhondx', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Yunae', class: 'Priest', level: 80, rank: 4 },
{ name: 'Fiammiferino', class: 'Mage', level: 80, rank: 4 },
{ name: 'Talamasca', class: 'Mage', level: 80, rank: 4 },
{ name: 'Yobay', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Itsboomie', class: 'Druid', level: 80, rank: 4 },
{ name: 'Druidprophet', class: 'Druid', level: 80, rank: 4 },
{ name: 'Salamdash', class: 'Mage', level: 80, rank: 4 },
{ name: 'Kaczoor', class: 'Druid', level: 80, rank: 4 },
{ name: 'Pandemics', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Kangax', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Vidaar', class: 'Druid', level: 80, rank: 4 },
{ name: 'Redevil', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Spreedhit', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Olas', class: 'Mage', level: 80, rank: 4 },
{ name: 'Lethoo', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Uta', class: 'Mage', level: 80, rank: 4 },
{ name: 'Survived', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Jotaleser', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Madresto', class: 'Druid', level: 80, rank: 4 },
{ name: 'Threvor', class: 'Mage', level: 80, rank: 4 },
{ name: 'Kvolss', class: 'Mage', level: 80, rank: 4 },
{ name: 'Chickfille', class: 'Druid', level: 80, rank: 4 },
{ name: 'Enhastterka', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Saahareej', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Medadobjo', class: 'Priest', level: 80, rank: 4 },
{ name: 'Pikadili', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Royales', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Rhaenery', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Diestroq', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Jimmywarr', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Firemeco', class: 'Mage', level: 80, rank: 4 },
{ name: 'Furyofdark', class: 'Priest', level: 80, rank: 4 },
{ name: 'Herzx', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Startklar', class: 'Druid', level: 80, rank: 4 },
{ name: 'Nicetrydidy', class: 'Mage', level: 80, rank: 4 },
{ name: 'Vandrelshamy', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Abmblack', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Sneakycrit', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Bigcat', class: 'Druid', level: 80, rank: 4 },
{ name: 'Byongg', class: 'Priest', level: 80, rank: 4 },
{ name: 'Horibull', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Stapho', class: 'Druid', level: 80, rank: 4 },
{ name: 'Discomisses', class: 'Priest', level: 80, rank: 4 },
{ name: 'Shonshon', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Moonspring', class: 'Druid', level: 80, rank: 4 },
{ name: 'Ppenetrator', class: 'Priest', level: 80, rank: 4 },
{ name: 'Cubarac', class: 'Druid', level: 80, rank: 4 },
{ name: 'Shynresto', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Fanofknives', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Gallay', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Lillivia', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Moutbelghoma', class: 'Priest', level: 80, rank: 4 },
{ name: 'Mimikom', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Korect', class: 'Druid', level: 80, rank: 4 },
{ name: 'Cailin', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Skalebza', class: 'Druid', level: 80, rank: 4 },
{ name: 'Buarac', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Reilya', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Nastynicki', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Oulaoula', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Halugaa', class: 'Mage', level: 80, rank: 4 },
{ name: 'Discopy', class: 'Priest', level: 80, rank: 4 },
{ name: 'Ljutkecap', class: 'Priest', level: 80, rank: 4 },
{ name: 'Theguide', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Cinderveil', class: 'Mage', level: 80, rank: 4 },
{ name: 'Hiightkiller', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Blueboss', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Mageyoto', class: 'Mage', level: 80, rank: 4 },
{ name: 'Cathrrina', class: 'Priest', level: 80, rank: 4 },
{ name: 'Freakyvenom', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Likeaspyxd', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Fynor', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Dimah', class: 'Druid', level: 80, rank: 4 },
{ name: 'Reveena', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Chambers', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Nnevermore', class: 'Priest', level: 80, rank: 4 },
{ name: 'Deathheall', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Killergayco', class: 'Mage', level: 80, rank: 4 },
{ name: 'Peenna', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Yalox', class: 'Mage', level: 80, rank: 4 },
{ name: 'Soulfacker', class: 'Mage', level: 80, rank: 4 },
{ name: 'Hornhof', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Cristianmur', class: 'Mage', level: 80, rank: 4 },
{ name: 'Ulrius', class: 'Mage', level: 80, rank: 4 },
{ name: 'Worgenmale', class: 'Priest', level: 80, rank: 4 },
{ name: 'Stabbunny', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Sliceandtot', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Gooddisco', class: 'Priest', level: 80, rank: 4 },
{ name: 'Goodshami', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Warbowier', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Moknahar', class: 'Druid', level: 80, rank: 4 },
{ name: 'Shyyshyy', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Shazeli', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Shmirgla', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Indesition', class: 'Priest', level: 80, rank: 4 },
{ name: 'Optimizovan', class: 'Druid', level: 80, rank: 4 },
{ name: 'Divni', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Zazbaz', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Luclock', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Xxlock', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Udaren', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Manbearcatz', class: 'Druid', level: 80, rank: 4 },
{ name: 'Jackdanielz', class: 'Druid', level: 80, rank: 4 },
{ name: 'Nordymtri', class: 'Mage', level: 80, rank: 4 },
{ name: 'Snipshot', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Snippala', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Snipdk', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Abitwook', class: 'Druid', level: 80, rank: 4 },
{ name: 'Dqd', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Duleewarr', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Vracharica', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Duleferal', class: 'Druid', level: 80, rank: 4 },
{ name: 'Dudupowah', class: 'Druid', level: 80, rank: 4 },
{ name: 'Selbel', class: 'Mage', level: 80, rank: 4 },
{ name: 'Eatmydisease', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Selkodk', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Paliqurec', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Oneeclick', class: 'Priest', level: 80, rank: 4 },
{ name: 'Toiletduck', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Holygankster', class: 'Priest', level: 80, rank: 4 },
{ name: 'Cylaxd', class: 'Druid', level: 80, rank: 4 },
{ name: 'Cylaxdk', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Cylaxr', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Cylaxw', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Duleshamy', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Isforsiran', class: 'Priest', level: 80, rank: 4 },
{ name: 'Jaddonlok', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Shadowhymn', class: 'Priest', level: 80, rank: 4 },
{ name: 'Elymin', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Halowarrior', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Wong', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Torkosan', class: 'Druid', level: 80, rank: 4 },
{ name: 'Lightsoutt', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Taurenirl', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Halomage', class: 'Mage', level: 80, rank: 4 },
{ name: 'Masele', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Halodk', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Holyshizt', class: 'Druid', level: 80, rank: 4 },
{ name: 'Pecaxd', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Soner', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Holyshizter', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Holyrogg', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Solarsurge', class: 'Druid', level: 80, rank: 4 },
{ name: 'Halodruid', class: 'Druid', level: 80, rank: 4 },
{ name: 'Miafang', class: 'Priest', level: 80, rank: 4 },
{ name: 'Shapeshiftop', class: 'Druid', level: 80, rank: 4 },
{ name: 'Halopaladin', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Frostcone', class: 'Mage', level: 80, rank: 4 },
{ name: 'Eellune', class: 'Druid', level: 80, rank: 4 },
{ name: 'Kitoljub', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Amonhad', class: 'Priest', level: 80, rank: 4 },
{ name: 'Tryxerrog', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Krealis', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Vandyk', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Kokanidja', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Halorogue', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Pljugetina', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Blistering', class: 'Mage', level: 80, rank: 4 },
{ name: 'Nekokaoja', class: 'Druid', level: 80, rank: 4 },
{ name: 'Gingerogue', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Syded', class: 'Druid', level: 80, rank: 4 },
{ name: 'Waawaalight', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Tezkra', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Butcheer', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Lunarvena', class: 'Druid', level: 80, rank: 4 },
{ name: 'Difens', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Sporadiclava', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Kiroronde', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Xtentacion', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Halowarlock', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Istolewallet', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Shinkinjin', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Kiljeaden', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Wlckedawe', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Peca', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Icecoldop', class: 'Mage', level: 80, rank: 4 },
{ name: 'Barstronk', class: 'Druid', level: 80, rank: 4 },
{ name: 'Ljutkan', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Extetdisco', class: 'Priest', level: 80, rank: 4 },
{ name: 'Nyyxxyrogue', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Mbcpriest', class: 'Priest', level: 80, rank: 4 },
{ name: 'Duknukeunh', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Stronker', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Ekson', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Extetdk', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Dorence', class: 'Mage', level: 80, rank: 4 },
{ name: 'Halohunter', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Totemca', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Shroudi', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Shroudidk', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Holyshizttwo', class: 'Priest', level: 80, rank: 4 },
{ name: 'Giannikaki', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Poisonrage', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Sliclock', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Storeman', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Simunida', class: 'Mage', level: 80, rank: 4 },
{ name: 'Slayeras', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Fokser', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Paulaabdul', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Siskos', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Peddopriest', class: 'Priest', level: 80, rank: 4 },
{ name: 'Fooffs', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Tiadres', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Tankinginc', class: 'Druid', level: 80, rank: 4 },
{ name: 'Onepunchorc', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Lululock', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Demologijaop', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Nordydruid', class: 'Druid', level: 80, rank: 4 },
{ name: 'Sulitshavi', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Optimizovaan', class: 'Mage', level: 80, rank: 4 },
{ name: 'Nogud', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Jumalflow', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Avaya', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Vodoopop', class: 'Priest', level: 80, rank: 4 },
{ name: 'Duledruid', class: 'Druid', level: 80, rank: 4 },
{ name: 'Slayeed', class: 'Druid', level: 80, rank: 4 },
{ name: 'Yusia', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Stihija', class: 'Mage', level: 80, rank: 4 },
{ name: 'Duknuke', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Nibirru', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Kilshot', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Legendoo', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Gizmogovno', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Halovodka', class: 'Druid', level: 80, rank: 4 },
{ name: 'Selkodruid', class: 'Druid', level: 80, rank: 4 },
{ name: 'Halocognac', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Donclaw', class: 'Druid', level: 80, rank: 4 },
{ name: 'Gicaprasica', class: 'Druid', level: 80, rank: 4 },
{ name: 'Grebblin', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Lubbenica', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Vukojarac', class: 'Mage', level: 80, rank: 4 },
{ name: 'Jamesfranco', class: 'Druid', level: 80, rank: 4 },
{ name: 'Demoservice', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Bezumen', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Nunay', class: 'Druid', level: 80, rank: 4 },
{ name: 'Halowhisky', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Healingzero', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Healthetankk', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Xduknuke', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Gangreenecat', class: 'Druid', level: 80, rank: 4 },
{ name: 'Livehack', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Pff', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Lalakers', class: 'Mage', level: 80, rank: 4 },
{ name: 'Sikezhina', class: 'Mage', level: 80, rank: 4 },
{ name: 'Liquidator', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Rikitakou', class: 'Mage', level: 80, rank: 4 },
{ name: 'Halobeer', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Haloliqueur', class: 'Priest', level: 80, rank: 4 },
{ name: 'Bibap', class: 'Druid', level: 80, rank: 4 },
{ name: 'Halotequila', class: 'Mage', level: 80, rank: 4 },
{ name: 'Mahadi', class: 'Druid', level: 80, rank: 4 },
{ name: 'Selkoo', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Davinchi', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Jvt', class: 'Druid', level: 80, rank: 4 },
{ name: 'Gruuglar', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Kurvestija', class: 'Mage', level: 80, rank: 4 },
{ name: 'Elenaril', class: 'Druid', level: 80, rank: 4 },
{ name: 'Pikabe', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Clickheroic', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Tryxerr', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Meltfaces', class: 'Priest', level: 80, rank: 4 },
{ name: 'Suljakovic', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Truckservice', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Zvezde', class: 'Druid', level: 80, rank: 4 },
{ name: 'Brutalusx', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Ziggolo', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Buttslicer', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Sllovk', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Lilcrazymage', class: 'Mage', level: 80, rank: 4 },
{ name: 'Sinju', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Ludimir', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Qvt', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Desnasisa', class: 'Druid', level: 80, rank: 4 },
{ name: 'Lookatmenine', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Sankaritar', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Predjator', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Zugartzti', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Jebenimage', class: 'Mage', level: 80, rank: 4 },
{ name: 'Markovina', class: 'Druid', level: 80, rank: 4 },
{ name: 'Sadmevidi', class: 'Druid', level: 80, rank: 4 },
{ name: 'Bloodyaxe', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Holyshiztten', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Yobatkal', class: 'Mage', level: 80, rank: 4 },
{ name: 'Straxrogue', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Righttit', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Yunbrez', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Yunica', class: 'Mage', level: 80, rank: 4 },
{ name: 'Yundasha', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Yunac', class: 'Druid', level: 80, rank: 4 },
{ name: 'Batonga', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Pitbulica', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Zacacicamaca', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Hollytwo', class: 'Druid', level: 80, rank: 4 },
{ name: 'Graga', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Duknukk', class: 'Mage', level: 80, rank: 4 },
{ name: 'Ministarxd', class: 'Priest', level: 80, rank: 4 },
{ name: 'Vukodlak', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Selkohunter', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Jotaab', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Gruubson', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Shotozero', class: 'Druid', level: 80, rank: 4 },
{ name: 'Stabbyfck', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Holyboli', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Siilaa', class: 'Priest', level: 80, rank: 4 },
{ name: 'Buliwyf', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Thralloc', class: 'Mage', level: 80, rank: 4 },
{ name: 'Belharza', class: 'Druid', level: 80, rank: 4 },
{ name: 'Tuskfury', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Maphala', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Snipwar', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Asidello', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Wulftusk', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Halobrandy', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Unholyriz', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Arannael', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Negotinka', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Northgueb', class: 'Druid', level: 80, rank: 4 },
{ name: 'Lmshadow', class: 'Priest', level: 80, rank: 4 },
{ name: 'Woogie', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Svetac', class: 'Priest', level: 80, rank: 4 },
{ name: 'Barmonn', class: 'Mage', level: 80, rank: 4 },
{ name: 'Illumiinarus', class: 'Mage', level: 80, rank: 4 },
{ name: 'Luxiel', class: 'Priest', level: 80, rank: 4 },
{ name: 'Jebeniirogue', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Mageforte', class: 'Mage', level: 80, rank: 4 },
{ name: 'Cylaxsp', class: 'Priest', level: 80, rank: 4 },
{ name: 'Ymortus', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Lucprist', class: 'Priest', level: 80, rank: 4 },
{ name: 'Hsalic', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Qracpalac', class: 'Mage', level: 80, rank: 4 },
{ name: 'Imabee', class: 'Druid', level: 80, rank: 4 },
{ name: 'Daney', class: 'Priest', level: 80, rank: 4 },
{ name: 'Sadowhart', class: 'Priest', level: 80, rank: 4 },
{ name: 'Varosan', class: 'Mage', level: 80, rank: 4 },
{ name: 'Krelel', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Salmonelica', class: 'Priest', level: 80, rank: 4 },
{ name: 'Ndmiiqt', class: 'Priest', level: 80, rank: 4 },
{ name: 'Jedenzdrugim', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Stormhart', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Snipmage', class: 'Mage', level: 80, rank: 4 },
{ name: 'Cipeczku', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Vindija', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Deznuts', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Titto', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Brezy', class: 'Mage', level: 80, rank: 4 },
{ name: 'Foodstampbro', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Ndmiibogaine', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Halogin', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Zenagotivna', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Ndmiice', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Zenavatrena', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Halorakija', class: 'Druid', level: 80, rank: 4 },
{ name: 'Eriney', class: 'Priest', level: 80, rank: 4 },
{ name: 'Skychaser', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Catalyzer', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Zenaratnica', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Bralson', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Atreffo', class: 'Druid', level: 80, rank: 4 },
{ name: 'Umbrra', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Sakezz', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Atreffinha', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Shadowatreff', class: 'Priest', level: 80, rank: 4 },
{ name: 'Lfgolds', class: 'Druid', level: 80, rank: 4 },
{ name: 'Rsalic', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Bernenko', class: 'Druid', level: 80, rank: 4 },
{ name: 'Izgoreo', class: 'Mage', level: 80, rank: 4 },
{ name: 'Jowanka', class: 'Priest', level: 80, rank: 4 },
{ name: 'Bartien', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Duknukesp', class: 'Priest', level: 80, rank: 4 },
{ name: 'Paintrainn', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Holybreach', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Duknukehunt', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Varimathres', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Dzokavac', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Rogherita', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Rizle', class: 'Druid', level: 80, rank: 4 },
{ name: 'Kakicu', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Erumog', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Rastapro', class: 'Druid', level: 80, rank: 4 },
{ name: 'Toxicdna', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Deadnice', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Cylaxs', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Buljisha', class: 'Mage', level: 80, rank: 4 },
{ name: 'Dragonpit', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Mecymagetwo', class: 'Mage', level: 80, rank: 4 },
{ name: 'Dukshamane', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Miagotth', class: 'Mage', level: 80, rank: 4 },
{ name: 'Cylaxm', class: 'Mage', level: 80, rank: 4 },
{ name: 'Miljann', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Mbchuntx', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Xesus', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Cylaxholy', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Ekimot', class: 'Priest', level: 80, rank: 4 },
{ name: 'Warghr', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Cocoburn', class: 'Mage', level: 80, rank: 4 },
{ name: 'Dyukfarmer', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Crazytwo', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Booxnadzija', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Fusqt', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Kittypaw', class: 'Druid', level: 80, rank: 4 },
{ name: 'Arwenna', class: 'Druid', level: 80, rank: 4 },
{ name: 'Sfrjvikiwar', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Tanaia', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Zobta', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Lightchaser', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Schambulance', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Sapphlre', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Elprofessor', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Rakhagul', class: 'Druid', level: 80, rank: 4 },
{ name: 'Rilelock', class: 'Warlock', level: 80, rank: 4 },
{ name: 'Gromdai', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Chainzpeed', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Lulainsixsix', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Hedwiig', class: 'Druid', level: 80, rank: 4 },
{ name: 'Duleedk', class: 'Death Knight', level: 80, rank: 4 },
{ name: 'Luvile', class: 'Hunter', level: 80, rank: 4 },
{ name: 'Holyshizttri', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Shroudidudu', class: 'Druid', level: 80, rank: 4 },
{ name: 'Remorless', class: 'Shaman', level: 80, rank: 4 },
{ name: 'Kezzu', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Duleepala', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Nightingstar', class: 'Druid', level: 80, rank: 4 },
{ name: 'Ifwarl', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Healmeon', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Pruseluskan', class: 'Druid', level: 80, rank: 4 },
{ name: 'Lucrogue', class: 'Rogue', level: 80, rank: 4 },
{ name: 'Yunzae', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Vizantija', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Magefraco', class: 'Mage', level: 80, rank: 4 },
{ name: 'Gelji', class: 'Priest', level: 80, rank: 4 },
{ name: 'Tyraantt', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Polarni', class: 'Druid', level: 80, rank: 4 },
{ name: 'Firetism', class: 'Mage', level: 80, rank: 4 },
{ name: 'Destroll', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Edina', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Wakbah', class: 'Paladin', level: 80, rank: 4 },
{ name: 'Keiforlon', class: 'Warrior', level: 80, rank: 4 },
{ name: 'Eleduknuke', class: 'Shaman', level: 80, rank: 4 }
];
